name: CalibreWebAutomated
version: "0.1.0"
slug: calibre_web_automated
description: Calibre-Web met automatische updates als Home Assistant add-on, gebaseerd op de officiële Docker image.
url: https://github.com/stouten/homeassistant-addons/tree/main/calibre-web-automated
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
init: false
ingress: true
ports: {}
ports_description: {}
startup: application
map:
  - config:rw
  - ssl:rw
  - addon_config:rw
  - media:rw
options:
  calibre_library_path: "/config/calibre-library"
schema:
  calibre_library_path: str
image: "crocodilestick/calibre-web-automated:{arch}"
